In [1]:
import pandas as pd  # data logic of patter , solve problem , decision making , improves ---> machine learning

In [2]:
df=pd.read_csv('preprocessing_dataset.csv')
df1=df.copy()

In [3]:
df2=df.copy()

In [4]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
lb.fit_transform(df['Gender']) # To 
df

      Name    Age Gender   Salary Department
0    Alice   25.0      F  50000.0         HR
1      Bob   30.0      M  60000.0    Finance
2  Charlie    NaN      M  55000.0         IT
3    David   40.0      M  58000.0         HR
4      Eve   22.0      F  52000.0         IT
5    Frank   35.0    NaN  61000.0    Finance
6    Grace  120.0      F      NaN    Finance
7    Henry   28.0      M  59000.0         HR
8      Ivy   29.0      F  63000.0         IT
9     Jack   27.0      M  62000.0    Finance

In [5]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['Encoded Gender']=lb.fit_transform(df['Gender']) # To identify the difference
df

      Name    Age Gender   Salary Department  Encoded Gender
0    Alice   25.0      F  50000.0         HR               0
1      Bob   30.0      M  60000.0    Finance               1
2  Charlie    NaN      M  55000.0         IT               1
3    David   40.0      M  58000.0         HR               1
4      Eve   22.0      F  52000.0         IT               0
5    Frank   35.0    NaN  61000.0    Finance               2
6    Grace  120.0      F      NaN    Finance               0
7    Henry   28.0      M  59000.0         HR               1
8      Ivy   29.0      F  63000.0         IT               0
9     Jack   27.0      M  62000.0    Finance               1

In [6]:
from sklearn.preprocessing import OneHotEncoder 
oh=OneHotEncoder(sparse_output=False)  # takes all data as array  and easy understanding
df['Encoded Gender']=oh.fit_transform(df[['Gender']]) 
df

      Name    Age Gender   Salary Department  Encoded Gender
0    Alice   25.0      F  50000.0         HR             1.0
1      Bob   30.0      M  60000.0    Finance             0.0
2  Charlie    NaN      M  55000.0         IT             0.0
3    David   40.0      M  58000.0         HR             0.0
4      Eve   22.0      F  52000.0         IT             1.0
5    Frank   35.0    NaN  61000.0    Finance             0.0
6    Grace  120.0      F      NaN    Finance             1.0
7    Henry   28.0      M  59000.0         HR             0.0
8      Ivy   29.0      F  63000.0         IT             1.0
9     Jack   27.0      M  62000.0    Finance             0.0

In [7]:
from sklearn.preprocessing import OneHotEncoder 
oh=OneHotEncoder(sparse_output=True)  #  Take as sparse matrix and takes ony non zero values difficult understanding
df[['Gen1','Gen2']]=oh.fit_transform(df[['Gender']])
df

ValueError: Columns must be same length as key

In [8]:
#get dummies
df11=pd.get_dummies(df,columns=['Gender'],drop_first=True) #Drop 
df11

      Name    Age   Salary Department  Encoded Gender  Gender_M
0    Alice   25.0  50000.0         HR             1.0     False
1      Bob   30.0  60000.0    Finance             0.0      True
2  Charlie    NaN  55000.0         IT             0.0      True
3    David   40.0  58000.0         HR             0.0      True
4      Eve   22.0  52000.0         IT             1.0     False
5    Frank   35.0  61000.0    Finance             0.0     False
6    Grace  120.0      NaN    Finance             1.0     False
7    Henry   28.0  59000.0         HR             0.0      True
8      Ivy   29.0  63000.0         IT             1.0     False
9     Jack   27.0  62000.0    Finance             0.0      True

In [9]:
# Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df1['Encoded Gender']=oe.fit_transform(df[['Gender']])
df1

      Name    Age Gender   Salary Department  Encoded Gender
0    Alice   25.0      F  50000.0         HR             0.0
1      Bob   30.0      M  60000.0    Finance             1.0
2  Charlie    NaN      M  55000.0         IT             1.0
3    David   40.0      M  58000.0         HR             1.0
4      Eve   22.0      F  52000.0         IT             0.0
5    Frank   35.0    NaN  61000.0    Finance             NaN
6    Grace  120.0      F      NaN    Finance             0.0
7    Henry   28.0      M  59000.0         HR             1.0
8      Ivy   29.0      F  63000.0         IT             0.0
9     Jack   27.0      M  62000.0    Finance             1.0